上传文件eTag校验
XGHeaven/nos-node-sdk pull request #8
Opened 2019-07-17 13:44 UTC by sookie2010

大佬~上次碰到的那个socket hang up的错误, 是我调用putObject的时候, body传的是ReadStream, 但是路径写错了, 于是node-fetch就报了这么个错, 但是它也不提示file not exists之类的信息, 导致没查到错误
于是我就加了个error事件的回调, 你看这样写合适吗?

还有就是写了一下eTag的校验, 不知道这么写是不是符合你的设计
技术渣代码写的不好, 大佬轻拍😓

2019-07-17 14:48 UTC, XGHeaven requested changes
另外补齐一下单测。
我有个地方写了 TODO: check etag，记得删除掉哦

2019-07-17 14:48 UTC, XGHeaven commented on src/exts/object.ts
> +        throw err
你确定这样有用 😏

2019-07-17 14:48 UTC, XGHeaven commented on src/client.ts
> +    const { resp, bodyMd5 } = await this._request(method, headers, resource, body)
我记得 resp 是可以拿到 req 的，你可以试试直接从 resp 的 req 中的 header 拿到 content-md5，从而和 etag 比较，不建议用这用这种解构的返回结构，不是很符合语义。

2019-07-18 00:42 UTC, sookie2010 commented on src/exts/object.ts
> +        throw err
这个我确定, 如果ReadStream指向了一个不存在的文件
node-fetch会长时间阻塞, 之后报一个socket hang up的错误
加上这个之后会报 no such file or directory, 至少提示信息很明确了

2019-07-18 00:43 UTC, sookie2010 commented on src/client.ts
> +    const { resp, bodyMd5 } = await this._request(method, headers, resource, body)
谢谢大佬指点, 我再改一下

2019-07-18 14:35 UTC, XGHeaven commented on src/exts/object.ts
> +        throw err
是这样的，throw err 应该是外面这个函数层面的，而不是说内部闭包的。你这样 throw err，其实和不监听 onerror 是一样的

2019-07-20 15:30 UTC, sookie2010 commented on src/exts/object.ts
> +        throw err
你说的也对, 不过我试过的结果是这样的
大佬你看~
![QQ20190720-232704](https://user-images.githubusercontent.com/16442323/61580541-ee436c80-ab45-11e9-9915-9d813f7d7242.png)
这个ReadStream指向的文件并不存在, 这是加了onerror的, 会抛出no such file or directory
![QQ20190720-233009](https://user-images.githubusercontent.com/16442323/61580572-5abe6b80-ab46-11e9-8b6a-2959f5553898.png)
如果不加的话就是这样的~
大佬你可以试一下呀

2019-07-25 04:03 UTC, XGHeaven commented on src/exts/object.ts
> +        throw err
抱歉，最近比较忙，没看到。
是可以抛出的。但是这个错误我无法在 `client.putObject().catch()` 捕捉到。

2022-11-03 02:58 UTC, closed without merging